### PR TITLE
Add gh action unittest

### PR DESCRIPTION
**Pull request by Rotzbua**
## Changes

* Migrate to `codeception 5`
* Add unittest to GH action test, run for every php version

## Note

* Includes #796
* Next possible feature: add acceptance tests to GH action

### CODE REVIEW

**Comment by CatoTH** [comment]
Ah, sorry for the conflict in CleanTranslationStringsTest.php . 
Skipping the failing tests for the voting majorities should not be necessary anymore now.

Apart from that: I will tag the new version in a few days (hopefully on weekend), and then we can switch to PHP 8 / the new codeception version here. Thanks you for driving this forward :-)

**Comment by CatoTH** [comment]
Is there a way to have the unit tests run only in one PHP version? It looks like each test pipeline takes like 3 minutes, and having a CPU run like 12 minutes for each commit feels a bit overkill... (not sure if I would run into a limitation, but uses energy still)

**Comment by Rotzbua** [comment]
> Is there a way to have the unit tests run only in one PHP version?

Code sometimes behaves differently with different PHP versions. I think it makes sense to fully test the officially supported versions with automated testing.

> It looks like each test pipeline takes like 3 minutes, and having a CPU run like 12 minutes for each commit feels a bit overkill... 

I removed the push trigger and limited to pull requests, release and manual trigger.

**Comment by CatoTH** [comment]
Hi,
I'm fine with the changes. I tested it locally. The unit tests run perfectly, only with the Acceptance tests there were a few issues. I fixed them in https://github.com/CatoTH/antragsgruen/pull/816/commits/99e359ee15d288974fe454f69e055bd43fd8059b , also rebased your commits onto main in https://github.com/CatoTH/antragsgruen/pull/816/commits . Some Acceptance tests are failing, but that is probably because actual errors in the program or the test cases, not because of the refactoring/upgrade. If you're fine with the modifications I made, I would merge them.

**Pull request merged**
