### PR TITLE
Add dependabot to autoreview and PR GH action updates

### PR DESCRIPTION
**Pull request by Rotzbua**
Let the bot do the chore of checking for updates.

### CODE REVIEW

**Comment by CatoTH** [comment]
@Rotzbua what would be the consequence of this? Would dependabot create PRs like it used to?

**Comment by Rotzbua** [comment]
Yes. But just for the Github Action scripts, because they have no easy to use dependency management.
The bot will **not** update npm or composer dependencies because those PRs can be really annoying.

**Comment by Rotzbua** [comment]
A PR looks like: https://github.com/miguelbalboa/rfid/pull/594

**Comment by CatoTH** [comment]
Okay, thank you for the explanation, and the PRs :-)

**Pull request merged**
