### PR TITLE
Dutch translation

### PR DESCRIPTION
**Pull request by m-rtijn**
I would like to use antragsgrün for a Dutch organization, but saw that there was not yet a Dutch translation. I intend on making one myself, but since a quick `wc -l` showed that there are more than 2000 translations to make that is quite a job to finish.

I figured that if I make a draft pull request maybe someone else can help me with this task :) Otherwise, I will work on it when I can, but that will take longer.

### CODE REVIEW

**Comment by CatoTH** [comment]
Hi!
I can't promise you too much on finding other Dutch-speaking collaborators... but just tell me if you think you came far enough to merge it.
I think, the most important parts would be base / consultation, and structure, motion, amendment. The least relevant (and biggest) is probably admin, as regular users won't see most of it.

**Comment by CatoTH** [comment]
@m-rtijn just out of interest: are you still working on it? After there seems to be a lot of work in this MR, it would be cool to merge it eventually. (don't forget to put yourself in the https://github.com/CatoTH/antragsgruen/blob/master/AUTHORS if you want :-) )

**Comment by m-rtijn** [comment]
@CatoTH I certainly intent to finish it at some point, but because I'm currently quite busy with other things it's taking longer than I would like.

**Comment by CatoTH** [comment]
I'm assuming, this probably won't be finished? Should I close it? Or are you still actively using the tool?

**Comment by m-rtijn** [comment]
Yeah sorry, I probably won't finish it. I won't delete it however, maybe someone someday can use it :)

**Comment by MickVolt** [comment]
Hi @m-rtijn  
I am not too familiar with how to do these kinds of translations. However, I do see how the work you've done adding all the message/nl files.  
Did you finish these files, if you do remember? Please help me understand how to find which messages aren't translated yet. (they seem pretty complete, in your files)  
Then, there are more files to translate, right? Outside the message folder?

It is probably a long shot, tagging you here. And I will seek further help. At least I am happy to have foud this commit, this will surely save us a lot of time.

So, thank you! For your work.

**Comment by m-rtijn** [comment]
@MickVolt All files that need to be translated are in messages. One would need to check if any new messages where added, but this does not seem to be the case (although I might have missed something). If you want, I can give you access to my repository so that you can continue on the translation. I can then reopen the PR and if it's done we can ask the maintainers if it's okay to merge :)

**Comment by MickVolt** [comment]
@m-rtijn that would be amazing!  
If I find more contributers, should I also ask you to provide them with access? Or can I download the files, have people change them, and then upload it again?

**Comment by m-rtijn** [comment]
@MickVolt Great! I've added you to my fork of this repo.

I think the most practical way to go would be for you to distribute the files that still need translation among any other contributors you find, and then upload them to my fork once fully translated. This limits the number of people that have to deal with git which is probably what you want to do (except if all others are already familiar with git).

**Comment by MickVolt** [comment]
@m-rtijn do you want me to fork your project so that you can see all the changes before merging my fork?  
Or shall I change all the files in your master repo?

**Comment by m-rtijn** [comment]
@MickVolt it is fine to just directly commit to the master branch of my repo!

**Comment by MickVolt** [comment]
Hi @m-rtijn I have changed all the files.  
The files Wizard, Admin, Speech, Manager, and Export are not 100% translated yet, but we'd like to push the translations to live in their current state.

@CatoTH would you be okay with merging the above texts thus far? If not on your main branch, then (for now) on the Volt instance?

**Comment by CatoTH** [comment]
@MickVolt  yes, would be fine. Two hints:
- larger blocks of untranslated strings (like in wizard.php) you can just leave out, as it will fall back to english anyway.
- you might need to create a /web/js/antragsgruen-nl.js , for the few strings where translations are not managed through the backend. The locale part there can probably be taken from node_modules/intl/locale-data/json/nl-NL.js

Just tell me when I should install this to your installation.

**Comment by MickVolt** [comment]
@CatoTH I will create that file and work on the translations.
Only, I do not understand the node_modules/intl/locale-data/json/nl-NL.js part. I don't see this folder structure in your repository

**Comment by MickVolt** [comment]
@CatoTH Done! Please install :).

**Comment by CatoTH** [comment]
Thanks to all of you! Do you want me to add you to the list of [https://github.com/CatoTH/antragsgruen/blob/main/AUTHORS](Authors)?

**Comment by m-rtijn** [comment]
> Thanks to all of you! Do you want me to add you to the list of [Authors](https://github.com/CatoTH/antragsgruen/blob/main/AUTHORS)?

Great that it got merged! For me, I don't have to mentioned in the authors file.

**Comment by MickVolt** [comment]
> Thanks to all of you! Do you want me to add you to the list of [Authors](https://github.com/CatoTH/antragsgruen/blob/main/AUTHORS)?

It would be cool to be mentioned there!  
Also, I'll have to make sure to finish the untranslated docs then :)

**Pull request merged**
