### PR TITLE
Raise minimum PHP version to 8.0

### PR DESCRIPTION
**Pull request by Rotzbua**
Tests need to be fixed to work with 8.1 and 8.2. Working on it.

### CODE REVIEW

**Comment by CatoTH** [comment]
Hi,
the original plan was to release 4.12 with 7.4 still, and raise the minimum to 8.0 with 4.13 - see https://github.com/CatoTH/antragsgruen/commit/318830edb20f07639113f3d6dc899ec84eb7fad0 . Is there a particular reason to require 8.0 sooner?
(I am planning to release 4.12 in the foreseeable future).

**Comment by Rotzbua** [comment]
Current `1.1.5``codeception/module-yii2` does only support:

> php: >=5.6.0 <=8.1 | ~8.1.0

https://packagist.org/packages/codeception/module-yii2#1.1.5

The next `1.1.6` does support 8.2 but requires codeception 5 which is php8 only.
https://packagist.org/packages/codeception/module-yii2#1.1.6
https://packagist.org/packages/codeception/codeception#5.0.10

**Comment by CatoTH** [comment]
Sorry for introducing conflicts again, wanted to have the latest Yii release. If you could rebase again, i would merge it on Monday or Tuesday.

**Comment by Rotzbua** [comment]
Rebased the PR and added `conflict` to composer to avoid unwanted upgrade of symfony libraries to v6 which would cause a conflict with optional dependency `simplesamlphp`.

**Pull request merged**
