### PR TITLE
Make amendments amendable

### PR DESCRIPTION
**Pull request by joriki**

### CODE REVIEW

**Comment by joriki** [comment]
Sorry, I was going to comment on this in detail but apparently already accidentally pressed a key to create the pull request -- comments will follow 😄

**Comment by CatoTH** [comment]
Ok, so I wait for the comments?
(I'm in vacation right now, so I don't really have a lot of time to look at it right now...)

**Comment by CatoTH** [comment]
@joriki Ich wäre übrigens inzwischen wieder aus dem Urlaub zurück :)

**Comment by CatoTH** [comment]
Falls du doch nochmal Lust hast, sag einfach nochmal Bescheid

**Pull request closed without merging**
